# The requiment to the data are yearly netcdf files
# e.g. 1995.nc, 1996.nc etc.


template = {'name': 'HOLIDROUGHT_SXI_183D',
            'version': (0, 1, 0),
            'path': '/p/scratch/cjibg31/jibg3105/data/HOLIDROUGHT/SXI/183D/',
            'type_file': 'netcdf',
            'year_start': 1995,
            'month_start': 7,
            'year_end': 2018,
            'month_end': 12,
            'leapday': False,
            'resolution_time': '8D',
            'grid': 'EU3',
            'variables': ['Temp'],
            'variable_names': {'Temp': 'TBOT'},
            'variable_dimensions': {'Temp': ['time', 'lat', 'lon']}, 
            'variable_units': {'Temp': 'degrees Celcius'},
            'mask_value': None}

SXI_183D_EU3_8daily = {'name': 'HOLIDROUGHT_SXI_183D',
                       'version': (0, 1, 0),
                       'path': '/p/scratch/cjibg31/jibg3105/data/HOLIDROUGHT/SXI/183D/',
                       'type_file': 'netcdf',
                       'year_start': 1995,
                       'month_start': 7,
                       'year_end': 2018,
                       'month_end': 12,
                       'leapday': False,
                       'resolution_time': '8D',
                       'grid': 'EU3',
                       'variables': ['SXI_GPP', 
                                     'SXI_ESOIL',
                                     'SXI_Tr',
                                     'SXI_BTRAN',
                                     'SXI_Gs',
                                     'SXI_Runoff',
                                     'SXI_SM_0',
                                     'SXI_SM_1',
                                     'SXI_SM_2',
                                     'SXI_SM_3',
                                     'SXI_SM_4',
                                     'SXI_SM_5',
                                     'SXI_SM_6',
                                     'SXI_SM_7',
                                     'SXI_SM_8',
                                     'SXI_SM_9',
                                     'SXI_SM_10',
                                     'SXI_SM_11',
                                     'SXI_SM_12',
                                     'SXI_SM_13',
                                     'SXI_SM_14',
                                     'SXI_SM_15',
                                     'SXI_SM_16',
                                     'SXI_SM_17',
                                     'SXI_SM_18',
                                     'SXI_SM_19',
                                     'SXI_WTD',
                                     'SXI_VPD',
                                     'SXI_P',
                                     'SXI_SM_r'],
                       'variable_names': {'SXI_GPP': 'SXI_GPP', 
                                          'SXI_ESOIL': 'SXI_ESOIL',
                                          'SXI_Tr': 'SXI_Tr',
                                          'SXI_BTRAN': 'SXI_BTRAN',
                                          'SXI_Gs': 'SXI_Gs',
                                          'SXI_Runoff': 'SXI_Runoff',
                                          'SXI_SM_0': 'SXI_SM_0',
                                          'SXI_SM_1': 'SXI_SM_1',
                                          'SXI_SM_2': 'SXI_SM_2',
                                          'SXI_SM_3': 'SXI_SM_3',
                                          'SXI_SM_4': 'SXI_SM_4',
                                          'SXI_SM_5': 'SXI_SM_5',
                                          'SXI_SM_6': 'SXI_SM_6',
                                          'SXI_SM_7': 'SXI_SM_7',
                                          'SXI_SM_8': 'SXI_SM_8',
                                          'SXI_SM_9': 'SXI_SM_9',
                                          'SXI_SM_10': 'SXI_SM_10',
                                          'SXI_SM_11': 'SXI_SM_11',
                                          'SXI_SM_12': 'SXI_SM_12',
                                          'SXI_SM_13': 'SXI_SM_13',
                                          'SXI_SM_14': 'SXI_SM_14',
                                          'SXI_SM_15': 'SXI_SM_15',
                                          'SXI_SM_16': 'SXI_SM_16',
                                          'SXI_SM_17': 'SXI_SM_17',
                                          'SXI_SM_18': 'SXI_SM_18',
                                          'SXI_SM_19': 'SXI_SM_19',
                                          'SXI_WTD': 'SXI_WTD',
                                          'SXI_VPD': 'SXI_VPD',
                                          'SXI_P': 'SXI_P',
                                          'SXI_SM_r': 'SXI_SM_r'},
                       'variable_dimensions': {'SXI_GPP': ['time', 'lat', 'lon'], 
                                               'SXI_ESOIL': ['time', 'lat', 'lon'],
                                               'SXI_Tr': ['time', 'lat', 'lon'],  
                                               'SXI_BTRAN': ['time', 'lat', 'lon'],
                                               'SXI_Gs': ['time', 'lat', 'lon'],
                                               'SXI_Runoff': ['time', 'lat', 'lon'],
                                               'SXI_SM_0': ['time', 'lat', 'lon'],
                                               'SXI_SM_1': ['time', 'lat', 'lon'],
                                               'SXI_SM_2': ['time', 'lat', 'lon'],
                                               'SXI_SM_3': ['time', 'lat', 'lon'],
                                               'SXI_SM_4': ['time', 'lat', 'lon'],
                                               'SXI_SM_5': ['time', 'lat', 'lon'],
                                               'SXI_SM_6': ['time', 'lat', 'lon'],
                                               'SXI_SM_7': ['time', 'lat', 'lon'],
                                               'SXI_SM_8': ['time', 'lat', 'lon'],
                                               'SXI_SM_9': ['time', 'lat', 'lon'],
                                               'SXI_SM_10': ['time', 'lat', 'lon'],
                                               'SXI_SM_11': ['time', 'lat', 'lon'],
                                               'SXI_SM_12': ['time', 'lat', 'lon'],
                                               'SXI_SM_13': ['time', 'lat', 'lon'],
                                               'SXI_SM_14': ['time', 'lat', 'lon'],
                                               'SXI_SM_15': ['time', 'lat', 'lon'],
                                               'SXI_SM_16': ['time', 'lat', 'lon'],
                                               'SXI_SM_17': ['time', 'lat', 'lon'],
                                               'SXI_SM_18': ['time', 'lat', 'lon'],
                                               'SXI_SM_19': ['time', 'lat', 'lon'],
                                               'SXI_WTD': ['time', 'lat', 'lon'],
                                               'SXI_VPD': ['time', 'lat', 'lon'],
                                               'SXI_P': ['time', 'lat', 'lon'],
                                               'SXI_SM_r': ['time', 'lat', 'lon'],}, 
                       'variable_units': {'SXI_GPP': 'dimensionless',
                                          'SXI_ESOIL': 'dimensionless',
                                          'SXI_Tr': 'dimensionless',
                                          'SXI_BTRAN': 'dimensionless',
                                          'SXI_Gs': 'dimensionless',
                                          'SXI_Runoff': 'dimensionless',
                                          'SXI_SM_0': 'dimensionless',
                                          'SXI_SM_1': 'dimensionless',
                                          'SXI_SM_2': 'dimensionless',
                                          'SXI_SM_3': 'dimensionless',
                                          'SXI_SM_4': 'dimensionless',
                                          'SXI_SM_5': 'dimensionless',
                                          'SXI_SM_6': 'dimensionless',
                                          'SXI_SM_7': 'dimensionless',
                                          'SXI_SM_8': 'dimensionless',
                                          'SXI_SM_9': 'dimensionless',
                                          'SXI_SM_10': 'dimensionless',
                                          'SXI_SM_11': 'dimensionless',
                                          'SXI_SM_12': 'dimensionless',
                                          'SXI_SM_13': 'dimensionless',
                                          'SXI_SM_14': 'dimensionless',
                                          'SXI_SM_15': 'dimensionless',
                                          'SXI_SM_16': 'dimensionless',
                                          'SXI_SM_17': 'dimensionless',
                                          'SXI_SM_18': 'dimensionless',
                                          'SXI_SM_19': 'dimensionless',
                                          'SXI_WTD': 'dimensionless',
                                          'SXI_VPD': 'dimensionless',
                                          'SXI_P': 'dimensionless',
                                          'SXI_SM_r': 'dimensionless'},
                       'mask_value': None}                     
                   